#!/usr/bin/env python3

import i3ipc

conn = i3ipc.Connection()

def on_floating(conn, evt):
    evt.container.command("resize set 1000 1000")
    evt.container.command("move position center")

conn.on("window::floating", on_floating)

conn.main();
